### ISSUE TITLE
2.0.0 alpha 2 seems to work just fine on 1.20.1?

### ISSUE THREAD

**Issue by noblereign** [Octol1ttle/FlightAssistant#12]
https://modrinth.com/mod/flightassistant/version/2.0.0-alpha.2
downloading this version and editing the .jar to allow 1.20.1 seems to work just fine, is there a reason why it's locked to 1.20.2?
if not it'd be nice if it could be officially changed to support 1.20.1 since there are still some people who're using it and might not know they can do this

**Comment by drafolin** [comment]
Just out of curiosity, did you try saving a flight plan?

**Comment by drafolin** [comment]
Oh wait, I think you can't do that in alpha 2, my bad lol

**Comment by Octol1ttle** [comment]
While it is true that Alpha 1 and Alpha 2 work on 1.20.0+, neither Modrinth nor CurseForge allow me to replace a version that has already been uploaded. Sorry :(

**Comment by noblereign** [comment]
unfortunate!!! thank you anyways 🫡
