### ISSUE TITLE
Sub par autopilot

### ISSUE THREAD

**Issue by SetOfAllSets** [Octol1ttle/FlightAssistant#13]
The autopilot will hit the fence at the end of a 20 block runway when it's destination is the first block.

**Comment by SetOfAllSets** [comment]
I think allowing a ground speed limit for landing might be a good idea

**Comment by Octol1ttle** [comment]
Can you send a reproduction world and flight plan?

**Comment by SetOfAllSets** [comment]
Upon updating cicada lib the mod suddenly started doing go arounds for the same flight plan, I've also gotten a better understanding of how to get a flight plan to work since then and realised why my flight plan wasn't working.
