### ISSUE TITLE
reactivation of alerts 1.21

### ISSUE THREAD

**Issue by mickael49300fr** [Octol1ttle/FlightAssistant#18]
hello, would it be possible to activate field alerts etc... when we are in creative, as was the case in 1.20.4, which was practical in my opinion, thank you
sorry I used google translate to write this message I'm not good in English

in creative
![javaw_zHRhOCBIlm](https://github.com/Octol1ttle/FlightAssistant/assets/7379217/e2f20f48-969d-409e-9af1-f646a78fa47d)

in survival
![javaw_KEUJxO0KpO](https://github.com/Octol1ttle/FlightAssistant/assets/7379217/2f576a80-e94f-4aa7-8845-dfab9e441ff7)

**Comment by mctaylors** [comment]
Hello, may I ask how this could be *practical* in Creative mode, where you are invincible?

**Comment by mickael49300fr** [comment]
I move 90% on my map in elytra, more practical and faster than creative flight, for moving from one area to another of my constructions
 the alerts help me know if I'm going to hit the wall etc...
as in the photo, the structure of a bridge that I made on 3000 blocks in length where I fly in between the beams of the bridge to go from one place to another

![2024-07-01_14 28 22](https://github.com/Octol1ttle/FlightAssistant/assets/7379217/baf007d5-bb8b-4802-ad91-c17ccd95d03a)

**Comment by mickael49300fr** [comment]
thanks you ;-)
