### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by Baichuan-qiao** [Octol1ttle/FlightAssistant#21]
I have created a Chinese localization file for this mod and hope it can be integrated into the official version.
[zh_cn.json](https://github.com/user-attachments/files/16618478/zh_cn.json)

**Comment by Baichuan-qiao** [comment]
I hope you can include me in the contributors list.

**Comment by Baichuan-qiao** [comment]
Thank you

**Comment by s-yh-china** [comment]
> I have created a Chinese localization file for this mod and hope it can be integrated into the official version. [zh_cn.json](https://github.com/user-attachments/files/16618478/zh_cn.json)

你可以试着打开一个pull requests，这是一种更好的方案
且在某些地方，可能可以更本土化一点，但你已经做的很好了

**Comment by mctaylors** [comment]
> 你可以试着打开一个pull requests，这是一种更好的方案
> 且在某些地方，可能可以更本土化一点，但你已经做的很好了

Please use English when you comment so everyone can understand what you mean.

**Comment by Octol1ttle** [comment]
> I hope you can include me in the contributors list.

Since you do not have any public commits on GitHub, I cannot mark you as an author of a commit. Please send a pull request with your translation file

**Comment by Baichuan-qiao** [comment]
I'm not a collaborator on this project and can't submit a pull request.

**Comment by Baichuan-qiao** [comment]
> > 我已经为这个mod创建了一个中文本地化文件，希望能把它集成到正式版中。[zh_cn.json](https://github.com/user-attachments/files/16618478/zh_cn.json)
> 
> 你可以试着打开一个pull requests，这是一种更好的方案 且在某些地方，可能可以更本土化一点，但你已经做的很好了

感谢您的提议，我之后会再次进行更新，尽请期待😊

**Comment by Baichuan-qiao** [comment]
> > I hope you can include me in the contributors list.
> 
> Since you do not have any public commits on GitHub, I cannot mark you as an author of a commit. Please send a pull request with your translation file

I'm not a collaborator on this project and can't submit a pull request.

**Comment by Baichuan-qiao** [comment]
> I have created a Chinese localization file for this mod and hope it can be integrated into the official version.

![image](https://github.com/user-attachments/assets/0fcf5c34-7983-47c5-9c18-ee44344af1a9)

**Comment by Octol1ttle** [comment]
You must create a fork first and push your changes to that fork. After that, you can create a pull request from your fork to this repository. https://opensource.com/article/19/7/create-pull-request-github

**Comment by Baichuan-qiao** [comment]
> 您必须先创建一个分叉，然后将您的更改推送到该分叉。之后，您可以从 fork 创建对此存储库的拉取请求。https://opensource.com/article/19/7/create-pull-request-github

oh, thank you
