### ISSUE TITLE
[Feature Request] Option to change the sound for warnings

### ISSUE THREAD

**Issue by DainXOR** [Octol1ttle/FlightAssistant#24]
I would like to change the default sounds for just an alarm instead of a voice, maybe it could be some option menu or select a local file, or both.

(Couldn't find a guide on how to post a request here, so yeah... Hope is good enough :P)

**Comment by Octol1ttle** [comment]
The mod relies on Minecraft's sound system to play the alert SFX, so there isn't a good way to allow sound file replacement in-game. You can, instead, use resourcepacks to replace the sounds (they are located in `assets/flightassistant/sounds`)

**Comment by DainXOR** [comment]
Thanks, i'll check into that

**Comment by Octol1ttle** [comment]
> Thanks, i'll check into that

Did resourcepacks solve your problem?

**Comment by DainXOR** [comment]
> > Thanks, i'll check into that
> 
> Did resourcepacks solve your problem?

Yes, it did, thanks for de info ^^
