### ISSUE TITLE
It will detect the light source block, causing the automatic driving to keep asking me to rise

### ISSUE THREAD

**Issue by cheerawab** [Octol1ttle/FlightAssistant#25]

**Comment by Octol1ttle** [comment]
Are you talking about the Light block in Operator Utilities?

Please say your Minecraft version, FlightAssistant version and, if possible, send a copy of the world where you can reproduce this problem.

**Comment by cheerawab** [comment]
https://drive.google.com/file/d/1davN1zBPLFJ1NtV3syqNbrcafzt3SdhV/view?usp=sharing

1.20
2.3.4

**Comment by Octol1ttle** [comment]
The warnings are caused by the surrounding walls, not the light blocks
