### ISSUE TITLE
Suggest for features/next version

### ISSUE THREAD

**Issue by FatherSarge** [Octol1ttle/FlightAssistant#3]
I saw you were working on a rebuild or rewrite, happy to see someone taking over flight hud properly.

I really like the features you've added, adds to the cool factor but I do have a request for whatever new version you work on...

A configurable menu that lets me permanently turn off certain features (preferably without the on screen text), specifically any feature that limits player input like the flight protections feature. For high intensity close/enclosed terrain flight the protections are more of a danger than a help. Flying through caves is exceptionally more dangerous :P 

Good luck on the next version!

**Comment by Octol1ttle** [comment]
Hello! Glad to see that you're interested in this project. Currently, I'm working on a rewrite (in the `a-new-beginning` branch) that will make the codebase a lot nicer, and a configuration screen is one of the planned features. 

In the current versions, you can temporarily turn off flight protections by pressing Enter on your numpad (changeable in keybinds menu). Hope that helps you while you wait!
