### ISSUE TITLE
Not sure if this is a bug or a feature ;)

### ISSUE THREAD

**Issue by djlawler** [Octol1ttle/FlightAssistant#4]
When I take off, after I'm in the air, I'm unable to pull back 'on the stick' after I pitch downward.
So if I take off, climb, then pitch downwards to fly level, I'm then unable to pull back UP and climb again.

**Comment by djlawler** [comment]
This seems to happen the -6 and -8 releases (did not try -7)

**Comment by Octol1ttle** [comment]
Are you trying to cross the stall protection threshold (marked as a red striped line in the center of the screen? Does activating fireworks and immediately pitching up temporarily resolve the issue?

If "no" is the answer to both questions, try turning flight protections off with Numpad Enter (changeable in keybinds menu) and write back the results

**Comment by Octol1ttle** [comment]
Closing due to lack of response
